name: Test Docker Metadata

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - meta
    tags:
      - 'v*'

jobs:
  release_default:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve docker configuration
        id: resolve-docker
        uses: actions/github-script@v7
        with:
          script: |
            return {
                image: "4chainstudio/ghaction-polygon",
                isDockerhub: true,
                isGhcr: false,
            }
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ fromJSON(steps.resolve-docker.outputs.result).image }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=semver,pattern={{raw}}
            type=raw,feat/spv-123_this_is_pretty_long_tag_and_it_should_be_truncated_below_128_chars_so_it_does_not_break_anything_when_pushed_to_docker_hub
            type=ref,event=push
            type=sha
          labels: |
            ${{ fromJSON(steps.resolve-docker.outputs.result).isDockerhub && format('org.opencontainers.image.url=https://hub.docker.com/r/{0}', fromJSON(steps.resolve-docker.outputs.result).image) }}
          flavor: latest=true
