name: Test Docker Metadata

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'main'
        type: string
      ref:
        description: 'Ref to release'
        required: false
        default: 'main'
        type: string
#  push:
#    branches:
#      - main
#      - meta
#    tags:
#      - 'v*'

run-name: "version = ${{ inputs.version }} | ref = ${{ inputs.ref }}"

jobs:
  release_default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || inputs.version }}
      - name: Resolve ref type
        # check based on the git repository if the inputs.version is a tag or branch or sha
        id: git-ref
        run: |
          value="${{ inputs.ref || inputs.version }}"
          echo "value=$value" > $GITHUB_OUTPUT
          type=$(git cat-file -t "$value")
          if [[ "$type" == "tag" ]]; then
            echo "type=tag" >> $GITHUB_OUTPUT
          elif [[ "$type" == "commit" && "$(git branch --show-current)" == "$value" ]]; then
            echo "type=branch" >> $GITHUB_OUTPUT
          else
            echo "type=sha" >> $GITHUB_OUTPUT
          fi

      - name: Print debug
        run: |
          echo "Ref: ${{ steps.git-ref.outputs.value }}"
          echo "Type: ${{ steps.git-ref.outputs.type }}"

#      - name: Resolve docker configuration
#        id: resolve-docker
#        uses: actions/github-script@v7
#        with:
#          script: |
#            return {
#                image: "4chainstudio/ghaction-polygon",
#                isDockerhub: true,
#                isGhcr: false,
#            }
#
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ fromJSON(steps.resolve-docker.outputs.result).image }}
#          tags: |
#            type=semver,pattern=v{{version}}
#            type=semver,pattern=v{{major}}.{{minor}}
#            type=semver,pattern=v{{major}}
#            type=semver,pattern={{raw}}
#            type=raw,feat/spv-123_this_is_pretty_long_tag_and_it_should_be_truncated_below_128_chars_so_it_does_not_break_anything_when_pushed_to_docker_hub
#            type=ref,event=branch,prefix=evbranch-
#            type=ref,event=tag,prefix=evtag-
#            type=sha
#          labels: |
#            ${{ fromJSON(steps.resolve-docker.outputs.result).isDockerhub && format('org.opencontainers.image.url=https://hub.docker.com/r/{0}', fromJSON(steps.resolve-docker.outputs.result).image) }}
#          flavor: latest=true
