name: "On push changes"

on:
  push:
    branches-ignore:
      - main
      - master

# TODO make inputs from this
env:
  GO_VERSION: '1.20'
  MAIN_FILE: 'cmd/main.go'

permissions:
  contents: write

jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RELEASE_KEY }}

      ################################################
      # Prepare programming language environment
      ################################################
      - uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}

      ############################################################
      # generate - run generation of go files if needed
      ############################################################

      # TODO: choose a common way to do that

      ############
      # go mod
      ############
      - name: Go Module tidy
        run: go mod tidy

     ############
     # YAML lint
     ############
      - name: Run yaml linter
        id: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1
        with:
          config_data: |
            extends: default
            ignore:
              - swagger.yaml
              - .golangci.yml
            rules:
              truthy:
                check-keys: false
              document-start:
                present: false
                level: warning
              line-length:
                max: 120
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: yamllint-logfile
          path: ${{ steps.yaml-lint.outputs.logfile }}

      - name: clean yaml-lint log
        if: always()
        run: rm ${{ steps.yaml-lint.outputs.logfile }}


      ############################################################
      # linelint - add new lines at the end of files if needed
      ############################################################

      # TODO: run a command to do so, or adjust (modify) linelint action for that

      ########################
      # lint & fix code style
      ########################

      # TODO: split golangci-lint configurations for code style and errors
      # consider unexcluding config files in a yaml lint step (above)

      ###################
      # Push changes
      ###################
      - name: "Commit & Push"
        id: commit
        if: always()
#        run: git status
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update generated files"
          default_author: github_actions
