name: On Release
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "Version of the app to release"
      os:
        description: "Comma separated list of OS for which the binary should be built"
        default: 'linux,darwin'
        required: false
        type: string
      go_version:
        required: false
        type: string
        default: '1.21'
        description: "Version of Go which should be used to perform the checks"
      cgo_enabled:
        required: false
        type: boolean
        default: false
        description: "Should set the CGO_ENABLED env and the compilers"
      release_binaries:
        required: false
        type: boolean
        default: true
        description: "If the packages with binaries should be attached to release"


env:
  OS_MAPPING: | 
    {
      'darwin': 'macos-latest',
      'linux': 'ubuntu-latest'
    }
    

jobs:
  resolve-config:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.os.outputs.result }}
      workflow: ${{ steps.workflow.outputs.result }}
    steps:
      - id: event
        uses: actions/github-script@v6
        with:
          script: |
            const push_tag = '${{ github.event }}'
            console.log(push_tag)
            return ''
      - id: os
        uses: actions/github-script@v6
        with:
          script: |
            const systems = '${{ inputs.os }}'
            const osToImage = ${{ env.OS_MAPPING }}
            
            return systems.split(',').map(os => osToImage[os]);
      - id: workflow
        uses: actions/github-script@v6
        with:
          script: |
            const workflowRef = '${{github.workflow_ref}}'
            const parts = workflowRef.split('@')[0].split('/')
            return {
              repository: `${{github.server_url}}/${parts[0]}/${parts[1]}`,
              owner: parts[0],
              repo_name: parts[1],
              file: parts.slice(2).join('/')
            }
              

  build:
    needs: [resolve-config]
    strategy:
      matrix:
        os: ${{ fromJSON(needs.resolve-config.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: ${{ inputs.cgo_enabled && '1' || '0' }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Build
        uses: bactions/build-go@v0
        with:
          go_version: ${{ inputs.go_version }}
      - name: "Create release if there isn't"
        if: inputs.release_binaries
        run: |
          GH_PAGER=cat gh release view ${{ inputs.version }} --json name \
          || gh release create ${{ inputs.version }} -t "Release ${{ inputs.version }}" --latest --draft -F dist/CHANGELOG.md 

      - name: Add binaries to release
        if: inputs.release_binaries
        run: |
          gh release upload ${{ inputs.version }} \
          dist/${{ github.event.repository.name }}*.tar.gz \
          dist/${{ github.event.repository.name }}*_checksums.txt \
          --clobber

  dockerize:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

