name: On Release
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      os:
        description: "Comma separated list of OS for which the binary should be built"
        default: 'linux,darwin'
        required: false
        type: string

env:
  OS_MAPPING: | 
    {
      'darwin': 'macos-latest',
      'linux': 'ubuntu-latest'
    }
    

jobs:
  resolve-config:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.os.outputs.result }}
    steps:
      - id: os
        uses: actions/github-script@v6
        with:
          script: |
            const systems = '${{ inputs.os }}'
            const osToImage = ${{ env.OS_MAPPING }}
            
            return systems.split(',').map(os => osToImage[os]);


  build:
    needs: [resolve-config]
    strategy:
      matrix:
        os: ${{ fromJSON(needs.resolve-config.outputs.os) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: "OS print"
        run: "uname"
