name: "PR"
on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  new-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v4
        with:
          #          github-token: ''
          git-user-name: 'Release Action'
          git-user-email: 'release-action@github.actions.com'
          preset: 'conventionalcommits'
          output-file: 'false'
          skip-tag: 'true'
          #          release-count: '10'
          #          version-file: './my_custom_version_file.json' // or .yml, .yaml, .toml, mix.exs
          #          version-path: 'path.to.version'

