name: Release

on:
  workflow_dispatch:
  
jobs:
  release_default:
    uses: bactions/workflows/.github/workflows/release-go-server.yml@norelease
    with:
      version: 218c88a
      os: linux
      cgo_enabled: true
      release_binaries: false
      release_create: false
