name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release_default:
    uses: ./.github/workflows/on-release.yaml
    with:
      version: ${{ github.ref_type }}
#  release_single:
#    uses: ./.github/workflows/on-release.yaml
#    with:
#      os: 'linux'
#      cgo_enabled: true
#      release_binaries: false
