name: Release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release_default:
    uses: ./.github/workflows/on-release.yaml
    with:
      version: ${{ github.ref_name }}
#      docker_registry: ghcr.io

#  release_single:
#    uses: ./.github/workflows/on-release.yaml
#    with:
#      os: 'linux'
#      cgo_enabled: true
#      release_binaries: false
