name: Release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release_default:
    uses: bactions/workflows/.github/workflows/release-go-server.yml@dockerfile
    with:
      version: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
