name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
    # TODO remove
    branches:
      - main
  workflow_dispatch:

env:
  CGO_ENABLED: 0

jobs:
  release_default:
    uses: ./.github/workflows/on-release.yaml
  release_single:
    uses: ./.github/workflows/on-release.yaml
    with:
      os: 'linux'
