name: Release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release_default:
    uses: ./.github/workflows/release-go-lib.yml
    with:
      version: ${{ github.ref_name }}
    secrets:
      #      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
