name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: ''
        type: string
      ref:
        description: 'Ref to release'
        required: false
        default: ''
        type: string
      release:
        description: 'Create a release'
        required: false
        default: false
        type: boolean
jobs:
  release_default:
    uses: bactions/workflows/.github/workflows/release-go-server.yml@norelease
    with:
      version: ${{ inputs.version }}
      ref: ${{ inputs.ref }}
      release_create: ${{ inputs.release }}
