name: "Tag version"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  new-tag:
    uses: bactions/workflows/.github/workflows/tag-new-version.yml@main
    with:
      deploy_key: ${{ secrets.RELEASE_KEY }}
