name: "Tag version"
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  new-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RELEASE_KEY }}

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ''
#          git-message: 'chore(release): {version}'
#          git-user-name: 'Awesome Changelog Action'
#          git-user-email: 'awesome_changelog@github.actions.com'
          preset: 'conventionalcommits'
#          tag-prefix: 'v'
#          output-file: 'MY_CUSTOM_CHANGELOG.md'
#          release-count: '10'
#          version-file: './my_custom_version_file.json' // or .yml, .yaml, .toml, mix.exs
#          version-path: 'path.to.version'
#          skip-on-empty: 'false'
          skip-version-file: 'true'
          skip-git-pull: 'true'
#          git-branch: 'my-maintenance-branch'
