name: "Tag version"
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  new-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RELEASE_KEY }}

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ''
          git-user-name: 'Release Action'
          git-user-email: 'release-action@github.actions.com'
          preset: 'conventionalcommits'
          skip-git-pull: 'true'
          output-file: 'false'
#          release-count: '10'
#          version-file: './my_custom_version_file.json' // or .yml, .yaml, .toml, mix.exs
#          version-path: 'path.to.version'
          ####
          # In case of Go release, where we don't have version file, the following two 'skip-*' flags must be set to true
          ####
#          skip-version-file: 'true'
#          skip-commit: 'true'


