name: Call Test Git Ref
run-name: "ref = ${{ inputs.ref }} | refname = ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to release'
        required: false
        default: ''
        type: string

jobs:
  release:
    uses: ./.github/workflows/resolve-git-ref.yaml
    with:
      version: ${{ inputs.ref || github.ref_name }}
