name: Call Test Git Ref
run-name: "Test version ${{ inputs.version || github.ref_name }} from ref  ${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to release'
        required: false
        default: ''
        type: string

jobs:
  release:
    uses: ./.github/workflows/resolve-git-ref.yaml
    with:
      version: ${{ inputs.version || github.ref_name }}
      ref: ${{ github.ref }}
