name: Print workflow call event
run-name: "Print workflow call for version ${{ inputs.version || github.ref_name }} from ref  ${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: ''
        type: string

jobs:
  release:
    uses: ./.github/workflows/print_event.yaml
    with:
      version: ${{ inputs.version || github.ref_name }}
